name: Publish to GitHub Packages

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --frozen

      - name: Build package
        run: uv build

      - name: Configure GitHub Packages repository
        run: |
          uv pip install twine
          echo "TWINE_USERNAME=__token__" >> $GITHUB_ENV
          echo "TWINE_PASSWORD=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "TWINE_REPOSITORY_URL=https://upload.pypi.org/legacy/" >> $GITHUB_ENV

      - name: Publish to GitHub Packages
        run: |
          uv run twine upload dist/* --repository-url https://upload.pypi.org/legacy/